name: Maven Package

on:
  push:
    tags:
      - "v*.*.*"
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: ossrh
          server-username: SONATYPE_USERNAME
          server-password: SONATYPE_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Deploy to Central
        run: mvn deploy
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          
      - name: Get Version
        run: |
          python3 -c "print('VERSION=v'+__import__('re').findall(r'<version>([^<]+)</version>',open('pom.xml','r',encoding='utf8').read())[0]" >> $GITHUB_ENV

      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          body: "Automatically generated release"
          tag_name: "${{ env.VERSION }}"
          name: "EpsilonEngine ${{ env.VERSION }}"
          files: |
            target/*.jar
